<Project Sdk="Microsoft.NET.Sdk">
	<!-- gotcha -->
	<PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <!-- La WPF solo referencia Negocio y Entidades. Nunca Datos. -->
  <ItemGroup>
    <ProjectReference Include="..\Grades.Business\Grades.Business.csproj" />
    <ProjectReference Include="..\Grades.Entities\Grades.Entities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>
</Project>
